import React from 'react';
import { ResponsiveContainer, BarChart, Bar, XAxis, YAxis, Tooltip, CartesianGrid } from 'recharts';
import { MapPin, TrendingUp, TrendingDown } from 'lucide-react';

export default function RegionalChart({ regionalData = {} }) {
  const { regional_summary = [] } = regionalData;

  const CustomTooltip = ({ active, payload, label }) => {
    if (active && payload && payload.length) {
      const data = payload[0].payload;
      return (
        <div className="bg-slate-900 border border-slate-700 p-3 rounded-xl shadow-xl text-xs">
          <p className="font-bold text-white mb-1">{label}</p>
          <p className="text-blue-400 font-semibold">Revenue: Rs. {data.revenue?.toLocaleString()}</p>
          <p className="text-emerald-400 font-semibold">Profit: Rs. {data.profit?.toLocaleString()}</p>
          <p className={`font-semibold ${data.growth_pct >= 0 ? 'text-emerald-400' : 'text-rose-400'}`}>
            DoD Growth: {data.growth_pct >= 0 ? '+' : ''}{data.growth_pct}%
          </p>
        </div>
      );
    }
    return null;
  };

  return (
    <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
      {/* Regional Revenue Bar Chart */}
      <div className="lg:col-span-2 glass-panel p-6 rounded-2xl border border-slate-800 shadow-xl shadow-slate-950/50">
        <div className="flex items-center justify-between mb-4">
          <div>
            <h3 className="text-base font-bold text-white flex items-center gap-2">
              <MapPin className="w-5 h-5 text-blue-400" /> Regional Performance Comparison
            </h3>
            <p className="text-xs text-slate-400">Total revenue generated by target sales territories</p>
          </div>
        </div>

        <div className="h-64 w-full">
          {regional_summary.length > 0 ? (
            <ResponsiveContainer width="100%" height="100%">
              <BarChart data={regional_summary} margin={{ top: 10, right: 10, left: -10, bottom: 0 }}>
                <CartesianGrid strokeDasharray="3 3" stroke="#1e293b" />
                <XAxis dataKey="region" stroke="#64748b" tick={{ fontSize: 11 }} />
                <YAxis stroke="#64748b" tick={{ fontSize: 11 }} />
                <Tooltip content={<CustomTooltip />} />
                <Bar dataKey="revenue" fill="#3b82f6" radius={[6, 6, 0, 0]} />
                <Bar dataKey="profit" fill="#10b981" radius={[6, 6, 0, 0]} />
              </BarChart>
            </ResponsiveContainer>
          ) : (
            <div className="h-full flex items-center justify-center text-slate-500 text-xs">
              No regional analytics available
            </div>
          )}
        </div>
      </div>

      {/* Regional Growth Breakdown Cards */}
      <div className="glass-panel p-6 rounded-2xl border border-slate-800 shadow-xl shadow-slate-950/50">
        <h3 className="text-base font-bold text-white mb-4">Territory Growth Summary</h3>

        <div className="space-y-3 max-h-64 overflow-y-auto pr-1">
          {regional_summary.map((reg, idx) => (
            <div key={idx} className="p-3 rounded-xl bg-slate-900/60 border border-slate-800 flex items-center justify-between">
              <div>
                <p className="text-xs font-bold text-slate-200">{reg.region}</p>
                <p className="text-[10px] text-slate-400">{reg.orders} Orders Today</p>
              </div>
              <div className="text-right">
                <p className="text-xs font-extrabold text-white">Rs. {reg.revenue?.toLocaleString()}</p>
                <div className={`inline-flex items-center gap-0.5 text-[10px] font-bold ${reg.growth_pct >= 0 ? 'text-emerald-400' : 'text-rose-400'}`}>
                  {reg.growth_pct >= 0 ? <TrendingUp className="w-3 h-3" /> : <TrendingDown className="w-3 h-3" />}
                  {reg.growth_pct >= 0 ? '+' : ''}{reg.growth_pct}%
                </div>
              </div>
            </div>
          ))}
        </div>
      </div>
    </div>
  );
}
